#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include "lwip/pbuf.h"
#include "lwip/tcp.h"
#include "principal_admin.h"

extern char http_response[8192];

void create_principal_admin_page(const char *mensagem_erro) {
     char bloco_erro[256] = "";

        if (mensagem_erro && strlen(mensagem_erro) > 0) {
            snprintf(bloco_erro, sizeof(bloco_erro),
                    "<div class=\"mensagem-erro\">%s</div>", mensagem_erro);
        }
        
    snprintf(http_response, sizeof(http_response),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html; charset=UTF-8\r\n\r\n"
        "<!DOCTYPE html>\n"
        "<html lang=\"pt-BR\">\n"
        "<head>\n"
        "<meta charset=\"UTF-8\">\n"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "<title>Painel do Administrador</title>\n"
        "<style>\n"
        "body {\n"
        "  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        "  background: linear-gradient(135deg, #f5f7fa 0%%, #c3cfe2 100%%);\n"
        "  margin: 0;\n"
        "  padding: 0;\n"
        "  color: #333;\n"
        "  display: flex;\n"
        "  flex-direction: column;\n"
        "  min-height: 100vh;\n"
        "}\n"
        ".barra-navegacao {\n"
        "  background-color: #166088;\n"
        "  color: white;\n"
        "  padding: 0.8rem 1rem;\n"
        "  display: flex;\n"
        "  justify-content: space-between;\n"
        "  align-items: center;\n"
        "}\n"
        ".lado-esquerdo {\n"
        "  display: flex;\n"
        "  align-items: center;\n"
        "  gap: 0.6rem;\n"
        "}\n"
        ".marca {\n"
        "  font-size: 1.2rem;\n"
        "  font-weight: bold;\n"
        "}\n"
        ".menu-navegacao {\n"
        "  display: flex;\n"
        "  gap: 0.8rem;\n"
        "}\n"
        ".item-navegacao {\n"
        "  color: white;\n"
        "  text-decoration: none;\n"
        "  padding: 0.4rem 0.8rem;\n"
        "  border-radius: 4px;\n"
        "  font-size: 0.9rem;\n"
        "  transition: background-color 0.2s;\n"
        "}\n"
        ".item-navegacao:hover {\n"
        "  background-color: rgba(255, 255, 255, 0.1);\n"
        "}\n"
        ".conteudo-principal {\n"
        "  flex: 1;\n"
        "  display: flex;\n"
        "  justify-content: center;\n"
        "  align-items: center;\n"
        "  padding: 1rem;\n"
        "  min-height: calc(100vh - 60px);\n"
        "}\n"
        ".caixa {\n"
        "  width: 100%%;\n"
        "  max-width: 340px;\n"
        "  padding: 1.5rem;\n"
        "  background: #fff;\n"
        "  border-radius: 12px;\n"
        "  box-shadow: 0 5px 15px rgba(0,0,0,0.1);\n"
        "  text-align: center;\n"
        "}\n"
        ".botao-logout {\n"
        "  background: #e53935;\n"
        "  color: white;\n"
        "  padding: 0.4rem 0.8rem;\n"
        "  border: none;\n"
        "  border-radius: 6px;\n"
        "  font-size: 0.9rem;\n"
        "  font-weight: bold;\n"
        "  cursor: pointer;\n"
        "  transition: opacity 0.2s;\n"
        "}\n"
        ".botao-logout:hover {\n"
        "  opacity: 0.9;\n"
        "}\n"
        ".mensagem-erro {\n"
        "  background: #f44336;\n"
        "  color: white;\n"
        "  padding: 12px;\n"
        "  margin-bottom: 15px;\n"
        "  border-radius: 8px;\n"
        "  font-size: 0.9rem;\n"
        "}\n"
        "h1 {\n"
        "  color: #166088;\n"
        "  font-size: 1.3rem;\n"
        "  margin-bottom: 1rem;\n"
        "}\n"
        ".exibir-senha {\n"
        "  font-size: 1.1rem;\n"
        "  letter-spacing: 0.2rem;\n"
        "  margin: 1rem 0;\n"
        "  padding: 0.6rem;\n"
        "  background: #f8f9fa;\n"
        "  border-radius: 6px;\n"
        "  min-height: 1.6rem;\n"
        "  user-select: none;\n"
        "}\n"
        ".teclado {\n"
        "  display: grid;\n"
        "  grid-template-columns: repeat(3, 1fr);\n"
        "  gap: 0.6rem;\n"
        "  margin: 1.2rem 0;\n"
        "}\n"
        ".tecla {\n"
        "  background: white;\n"
        "  border: 2px solid #4a6fa5;\n"
        "  border-radius: 50%%;\n"
        "  width: 55px;\n"
        "  height: 55px;\n"
        "  display: flex;\n"
        "  justify-content: center;\n"
        "  align-items: center;\n"
        "  font-size: 1.1rem;\n"
        "  font-weight: bold;\n"
        "  color: #4a6fa5;\n"
        "  cursor: pointer;\n"
        "  transition: all 0.2s;\n"
        "  user-select: none;\n"
        "  margin: 0 auto;\n"
        "}\n"
        ".tecla:hover {\n"
        "  background: #4a6fa5;\n"
        "  color: white;\n"
        "}\n"
        ".acoes {\n"
        "  display: flex;\n"
        "  flex-direction: column;\n"
        "  align-items: center;\n"
        "  gap: 0.6rem;\n"
        "  margin-top: 1.2rem;\n"
        "}\n"
        ".botoes-superiores {\n"
        "  display: flex;\n"
        "  justify-content: space-between;\n"
        "  width: 100%%;\n"
        "  gap: 0.6rem;\n"
        "  margin-bottom: 0.8rem;\n"
        "}\n"
        ".botao {\n"
        "  padding: 0.5rem 0.8rem;\n"
        "  border: none;\n"
        "  border-radius: 6px;\n"
        "  font-size: 0.9rem;\n"
        "  font-weight: 600;\n"
        "  cursor: pointer;\n"
        "  transition: all 0.2s;\n"
        "  flex: 1;\n"
        "}\n"
        ".botao-enviar {\n"
        "  background: #4CAF50;\n"
        "  color: white;\n"
        "}\n"
        ".botao-limpar {\n"
        "  background: #9e9e9e;\n"
        "  color: white;\n"
        "}\n"
        ".botao-trancar {\n"
        "  background: #f44336;\n"
        "  color: #fff;\n"
        "  width: 100%%;\n"
        "  max-width: 200px;\n"
        "}\n"
        ".botao:hover {\n"
        "  opacity: 0.9;\n"
        "}\n"
        "@media (max-width: 480px) {\n"
        "  .caixa {\n"
        "    padding: 1rem;\n"
        "    margin-top: 4rem;\n"
        "  }\n"
        "  .tecla {\n"
        "    width: 45px;\n"
        "    height: 45px;\n"
        "    font-size: 0.9rem;\n"
        "  }\n"
        "  .barra-navegacao {\n"
        "    flex-direction: column;\n"
        "    align-items: center;\n"
        "    gap: 0.5rem;\n"
        "  }\n"
        "  .marca {\n"
        "    font-size: 1.3rem;\n"
        "    text-align: center;\n"
        "    width: 100%%;\n"
        "  }\n"
        "  .menu-navegacao {\n"
        "    flex-direction: column;\n"
        "    width: 100%%;\n"
        "    align-items: center;\n"
        "  }\n"
        "  .item-navegacao {\n"
        "    display: block;\n"
        "    width: 100%%;\n"
        "    text-align: center;\n"
        "    padding: 0.6rem 0;\n"
        "    border-radius: 6px;\n"
        "    font-size: 1rem;\n"
        "  }\n"
        "  .conteudo-principal {\n"
        "    min-height: auto;\n"
        "    padding-top: 0.5rem;\n"
        "    padding-bottom: 1rem;\n"
        "  }\n"
        "}\n"
        "</style>\n"
        "</head>\n"
        "<body>\n"
        "<div class=\"container-administrador\">\n"
        "<nav class=\"barra-navegacao\">\n"
        "<div class=\"lado-esquerdo\">\n"
        "  <form method=\"POST\" action=\"/logout\">\n"
        "    <button type=\"submit\" class=\"botao botao-logout\">Sair</button>\n"
        "  </form>\n"
        "  <div class=\"marca\">Painel do Administrador</div>\n"
        "</div>\n"
        "<div class=\"menu-navegacao\">\n"
        "<a href=\"/cadastrar-usuario-page\" class=\"item-navegacao\">Cadastrar Usuário</a>\n"
        "<a href=\"/ver-logs-page\" class=\"item-navegacao\">Acessar Logs</a>\n"
        "<a href=\"/alterar-senha\" class=\"item-navegacao\">Alterar Senha da Fechadura</a>\n"
        "<a href=\"/excluir-usuario\" class=\"item-navegacao\">Excluir Usuário</a>\n"
        "</div>\n"
        "</nav>\n"
        "<div class=\"conteudo-principal\">\n"
        "<div class=\"caixa\">\n"
        "<h1>Insira a senha da fechadura</h1>\n"
        "%s\n"
        "<form method=\"POST\" action=\"/senha-fechadura\">\n"
        "<div class=\"exibir-senha\" id=\"campoSenha\">&nbsp;</div>\n"
        "<input type=\"password\" name=\"senha\" id=\"inputSenha\" style=\"position:absolute; left:-9999px;\" required maxlength=\"6\">\n"
        "<div class=\"teclado\">\n"
        "<div class=\"tecla\" onclick=\"adicionarNumero('7')\">7</div>\n"
        "<div class=\"tecla\" onclick=\"adicionarNumero('8')\">8</div>\n"
        "<div class=\"tecla\" onclick=\"adicionarNumero('9')\">9</div>\n"
        "<div class=\"tecla\" onclick=\"adicionarNumero('4')\">4</div>\n"
        "<div class=\"tecla\" onclick=\"adicionarNumero('5')\">5</div>\n"
        "<div class=\"tecla\" onclick=\"adicionarNumero('6')\">6</div>\n"
        "<div class=\"tecla\" onclick=\"adicionarNumero('1')\">1</div>\n"
        "<div class=\"tecla\" onclick=\"adicionarNumero('2')\">2</div>\n"
        "<div class=\"tecla\" onclick=\"adicionarNumero('3')\">3</div>\n"
        "</div>\n"
        "<div class=\"acoes\">\n"
        "<div class=\"botoes-superiores\">\n"
        "<button type=\"button\" class=\"botao botao-limpar\" onclick=\"limparSenha()\">Limpar</button>\n"
        "<button type=\"submit\" class=\"botao botao-enviar\">Destrancar</button>\n"
        "</div>\n"
        "</form>\n"
        "<form method=\"POST\" action=\"/trancar-fechadura\" style=\"width: 100%%; text-align: center;\">\n"
        "<button type=\"submit\" class=\"botao botao-trancar\">Trancar</button>\n"
        "</form>\n"
        "</div>\n"
        "</div>\n"
        "</div>\n"
        "<script>\n"
        "let senhaAtual = '';\n"
        "const campoSenha = document.getElementById('campoSenha');\n"
        "const inputSenha = document.getElementById('inputSenha');\n"
        "function adicionarNumero(num) {\n"
        "  if (senhaAtual.length < 6) {\n"
        "    senhaAtual += num;\n"
        "    atualizarCampoSenha();\n"
        "  }\n"
        "}\n"
        "function limparSenha() {\n"
        "  senhaAtual = '';\n"
        "  atualizarCampoSenha();\n"
        "}\n"
        "function atualizarCampoSenha() {\n"
        "  campoSenha.textContent = senhaAtual.replace(/./g, '•') || '\\u00A0';\n"
        "  inputSenha.value = senhaAtual;\n"
        "}\n"
        "</script>\n"
        "</body>\n"
        "</html>\n",
          bloco_erro  
    );
}
